swiftlint_version: 0.43.1

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
    - unused_declaration
    - unused_import

deployment_target:
    iOS_deployment_target: 10.0

closure_body_length:
    warning: 30
    error: 30

identifier_name:
    max_length: 150

file_length:
    warning: 1500
    error: 1500
    #ignore_comment_only_lines: true

function_body_length:
    warning: 200
    error: 200

function_parameter_count:
    warning: 8
    error: 8

line_length:
    warning: 1000
    error: 1000

type_body_length:
    warning: 1000
    error: 1000

type_name:
    max_length: 150

cyclomatic_complexity:
    warning: 30
    error: 30

opt_in_rules:
    - closure_body_length
    # - closure_end_indentation # disabled, because xcode's block indentation depends on `[weak self]`
    - closure_spacing
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - discouraged_optional_boolean
    - duplicate_imports
    - empty_collection_literal
    - empty_count
    - empty_string
    - explicit_init
    - fatal_error_message
    # - file_name # disabled, because results are not consistent
    # - file_header
    - first_where
    - force_unwrapping
    - identical_operands
    # - indentation_width # disabled, because multiline arguments are not recognized properly
    - inert_defer
    - last_where
    - legacy_random
    - let_var_whitespace
    # - multiline_arguments
    - multiline_parameters
    - multiple_closures_with_trailing_closure
    - no_space_in_method_call
    # - object_literal
    - operator_usage_whitespace
    - optional_enum_case_matching
    - prefer_self_type_over_type_of_self
    - prefixed_toplevel_constant
    - private_action
    - private_over_fileprivate
    - prohibited_super_call
    - reduce_into
    - redundant_nil_coalescing
    - single_test_class
    - sorted_first_last
    # - sorted_imports
    - strict_fileprivate
    - strong_iboutlet
    - toggle_bool
    # - type_contents_order # https://realm.github.io/SwiftLint/type_contents_order.html
    # - trailing_closure
    - unowned_variable_capture
    - unused_setter_value
    - vertical_parameter_alignment_on_call
    - yoda_condition
